# fix lineendings in Windows
init:
  - git config --global core.autocrlf input

environment:
  RUST_BACKTRACE: 1
  matrix:
  - TARGET: x86_64-pc-windows-msvc
  - TARGET: i686-pc-windows-msvc
  - TARGET: i686-pc-windows-gnu

install:
  - appveyor-retry appveyor DownloadFile "https://static.rust-lang.org/rustup/dist/%TARGET%/rustup-init.exe" -FileName rustup-init.exe
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin

build: false

build_script:
  - rustc -V
  - cargo -V
  - cargo build
  - cargo test
